name: cd_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest
  # because matplotlib>10 installs pyside6 which seems to have
  # compatibility problems with vscode plotting
  - matplotlib<3.10
  - numpy
  - scikit-learn
  - scipy
  - pinocchio
  - meshcat-python
  - pandas
  - seaborn
  - aligator=0.12
  - pytorch
  - torchvision
  - ipykernel
  - gymnasium[mujoco]
  - lightning
  - pip:
    - stable-baselines3
    - pytest
    - tensorboard
    - tensorboardX
