[workspace]
name = "cd_project"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = "3.12.*"
pytest = "*"
matplotlib = "<3.10"
numpy = "*"
scikit-learn = "*"
scipy = "*"
pandas = "*"
seaborn = "*"
pytorch = "*"
torchvision = "*"
ipykernel = "*"
lightning = "*"
sktime = "*"
numba = ">=0.64.0,<0.65"
ruff = "*"
pybullet = ">=3.25,<4"
umap-learn = ">=0.5.11,<0.6"
tqdm = "4.66.1.*"
jupyterlab = ">=4.5.6,<5"
cython = ">=3.2.4,<4"
uv = ">=0.11.2,<0.12"
transformers = ">=5.5.0,<6"
huggingface_hub = ">=1.8.0,<2"
python-annoy = "*"
plotly = ">=6.6.0,<7"
tyro = ">=1.0.13,<2"
jaxtyping = ">=0.3.7,<0.4"

[pypi-dependencies]
stable-baselines3 = "*"
sb3-contrib = "*"
gymnasium = { version = "*", extras = ["mujoco"] }
tensorboard = "*"
tensorboardX = "*"
upkie = "*"
cd_project = { path = ".", editable = true }
sigkerax = ">=0.2.1, <0.3"
claudette = ">=0.3.14, <0.4"
anomalib = ">=2.3.1, <3"
flowjax = ">=19.0.0, <20"
pacmap = ">=0.7, <0.8"
phate = ">=1.0, <2"

[tasks]
gen_data = "python scripts/regen_datasets.py"
tune = "rm -rf results/tuned && python scripts/tune.py --env all"

[target.linux-64.dependencies]
cuda-nvcc = ">=12.6.3"

[target.linux-64.pypi-dependencies]
jax = {version = "*", extras = ["cuda12"]}

